//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace W41_UDPBroadcastReciever_RPSensor.RPSensorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RPSensorService.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSensorData", ReplyAction="http://tempuri.org/IService1/AddSensorDataResponse")]
        int AddSensorData(int LightData, int TempData, int PotData, int AnalogData, System.DateTime Time);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddSensorData", ReplyAction="http://tempuri.org/IService1/AddSensorDataResponse")]
        System.Threading.Tasks.Task<int> AddSensorDataAsync(int LightData, int TempData, int PotData, int AnalogData, System.DateTime Time);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : W41_UDPBroadcastReciever_RPSensor.RPSensorService.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<W41_UDPBroadcastReciever_RPSensor.RPSensorService.IService1>, W41_UDPBroadcastReciever_RPSensor.RPSensorService.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public int AddSensorData(int LightData, int TempData, int PotData, int AnalogData, System.DateTime Time) {
            return base.Channel.AddSensorData(LightData, TempData, PotData, AnalogData, Time);
        }
        
        public System.Threading.Tasks.Task<int> AddSensorDataAsync(int LightData, int TempData, int PotData, int AnalogData, System.DateTime Time) {
            return base.Channel.AddSensorDataAsync(LightData, TempData, PotData, AnalogData, Time);
        }
    }
}
